// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Naibbe;

#nullable disable

namespace Naibbe.Migrations
{
    [DbContext(typeof(NaibbeDbContext))]
    [Migration("20260310180102_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Naibbe.TranslationTable", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("TranslationTables");
                });

            modelBuilder.Entity("Naibbe.TranslationTableRow", b =>
                {
                    b.Property<string>("Letter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationTableName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unigram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Letter");

                    b.HasIndex("TranslationTableName");

                    b.ToTable("TranslationTableRow");
                });

            modelBuilder.Entity("Naibbe.TranslationTableRow", b =>
                {
                    b.HasOne("Naibbe.TranslationTable", null)
                        .WithMany("Data")
                        .HasForeignKey("TranslationTableName");
                });

            modelBuilder.Entity("Naibbe.TranslationTable", b =>
                {
                    b.Navigation("Data");
                });
#pragma warning restore 612, 618
        }
    }
}
