//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d9.gnc.core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d9.gnc.core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter,Unigram,Prefix,Suffix
        ///A,&lt;ol&gt;,&lt;sh&gt;,&lt;aiin&gt;
        ///B,&lt;qokchdy&gt;,&lt;dol&gt;,&lt;l&gt;
        ///C,&lt;chey&gt;,&lt;lch&gt;,&lt;eeey&gt;
        ///D,&lt;cheey&gt;,&lt;o&gt;,&lt;eeody&gt;
        ///E,&lt;chedy&gt;,&lt;ch&gt;,&lt;edy&gt;
        ///F,&lt;qokchey&gt;,&lt;shckh&gt;,&lt;eam&gt;
        ///G,&lt;qokchy&gt;,&lt;cph&gt;,&lt;g&gt;
        ///H,&lt;qokchedy&gt;,&lt;qotch&gt;,&lt;eedal&gt;
        ///I,&lt;shedy&gt;,&lt;k&gt;,&lt;dy&gt;
        ///L,&lt;qokal&gt;,&lt;cth&gt;,&lt;es&gt;
        ///M,&lt;qokar&gt;,&lt;l&gt;,&lt;ody&gt;
        ///N,&lt;daiin&gt;,&lt;opch&gt;,&lt;al&gt;
        ///O,&lt;aiin&gt;,&lt;r&gt;,&lt;or&gt;
        ///P,&lt;qoky&gt;,&lt;dch&gt;,&lt;edar&gt;
        ///Q,&lt;qokol&gt;,&lt;dl&gt;,&lt;iin&gt;
        ///R,&lt;qokeedy&gt;,&lt;t&gt;,&lt;eedy&gt;
        ///S,&lt;qokeey&gt;,&lt;lk&gt;,&lt;ar&gt;
        ///T,&lt;qokaiin&gt;,&lt;qok&gt;,&lt;y&gt;
        ///U,&lt;qokain&gt;,&lt;ot&gt;,&lt;eey&gt;
        ///V,&lt;qokey&gt;,&lt;qockh&gt;,&lt;edor&gt;
        ///X,&lt;qokor&gt;,&lt;lpch&gt;,&lt;edo&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranslationTable_Alpha {
            get {
                return ResourceManager.GetString("TranslationTable_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter,Unigram,Prefix,Suffix
        ///A,&lt;or&gt;,&lt;yt&gt;,&lt;eol&gt;
        ///B,&lt;okchdy&gt;,&lt;qolch&gt;,&lt;ory&gt;
        ///C,&lt;okedy&gt;,&lt;tsh&gt;,&lt;r&gt;
        ///D,&lt;cheedy&gt;,&lt;dal&gt;,&lt;eeos&gt;
        ///E,&lt;ar&gt;,&lt;ok&gt;,&lt;ey&gt;
        ///F,&lt;okchey&gt;,&lt;rsh&gt;,&lt;iiin&gt;
        ///G,&lt;okchy&gt;,&lt;solch&gt;,&lt;eols&gt;
        ///H,&lt;okchedy&gt;,&lt;oiin&gt;,&lt;er&gt;
        ///I,&lt;qokedy&gt;,&lt;yk&gt;,&lt;eody&gt;
        ///L,&lt;okal&gt;,&lt;ypch&gt;,&lt;eedaiin&gt;
        ///M,&lt;okar&gt;,&lt;s&gt;,&lt;edain&gt;
        ///N,&lt;dal&gt;,&lt;kch&gt;,&lt;d&gt;
        ///O,&lt;al&gt;,&lt;lkch&gt;,&lt;eos&gt;
        ///P,&lt;oky&gt;,&lt;qoksh&gt;,&lt;as&gt;
        ///Q,&lt;okol&gt;,&lt;of&gt;,&lt;als&gt;
        ///R,&lt;okeedy&gt;,&lt;tch&gt;,&lt;daiin&gt;
        ///S,&lt;okeey&gt;,&lt;or&gt;,&lt;eeo&gt;
        ///T,&lt;okaiin&gt;,&lt;pch&gt;,&lt;am&gt;
        ///U,&lt;okain&gt;,&lt;olk&gt;,&lt;eo&gt;
        ///V,&lt;okey&gt;,&lt;daly&gt;,&lt;sy&gt;
        ///X,&lt;okor&gt;,&lt;f&gt;,&lt;eeeos&gt;
        ///Y,&lt;o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranslationTable_Beta1 {
            get {
                return ResourceManager.GetString("TranslationTable_Beta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter,Unigram,Prefix,Suffix
        ///A,&lt;qol&gt;,&lt;olch&gt;,&lt;air&gt;
        ///B,&lt;otchdy&gt;,&lt;dor&gt;,&lt;oy&gt;
        ///C,&lt;lkaiin&gt;,&lt;y&gt;,&lt;aiiin&gt;
        ///D,&lt;lkain&gt;,&lt;otsh&gt;,&lt;dol&gt;
        ///E,&lt;dar&gt;,&lt;ol&gt;,&lt;ol&gt;
        ///F,&lt;otchey&gt;,&lt;ly&gt;,&lt;daiiin&gt;
        ///G,&lt;otchy&gt;,&lt;ssh&gt;,&lt;saiin&gt;
        ///H,&lt;otchedy&gt;,&lt;aly&gt;,&lt;eaiin&gt;
        ///I,&lt;shey&gt;,&lt;qot&gt;,&lt;eor&gt;
        ///L,&lt;otal&gt;,&lt;sch&gt;,&lt;edol&gt;
        ///M,&lt;otar&gt;,&lt;shcth&gt;,&lt;dain&gt;
        ///N,&lt;dain&gt;,&lt;okch&gt;,&lt;oiin&gt;
        ///O,&lt;ain&gt;,&lt;lt&gt;,&lt;eeedy&gt;
        ///P,&lt;oty&gt;,&lt;qolk&gt;,&lt;eeod&gt;
        ///Q,&lt;otol&gt;,&lt;dary&gt;,&lt;edaiiin&gt;
        ///R,&lt;oteedy&gt;,&lt;qopch&gt;,&lt;s&gt;
        ///S,&lt;oteey&gt;,&lt;sol&gt;,&lt;edal&gt;
        ///T,&lt;otaiin&gt;,&lt;od&gt;,&lt;edaiin&gt;
        ///U,&lt;otain&gt;,&lt;p&gt;,&lt;eeol&gt;
        ///V,&lt;otey&gt;,&lt;sar&gt;,&lt;sdy&gt;
        ///X,&lt;otor&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranslationTable_Beta2 {
            get {
                return ResourceManager.GetString("TranslationTable_Beta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter,Unigram,Prefix,Suffix
        ///A,&lt;chdy&gt;,&lt;ls&gt;,&lt;ed&gt;
        ///B,&lt;sheckhy&gt;,&lt;octh&gt;,&lt;eoy&gt;
        ///C,&lt;shckhy&gt;,&lt;och&gt;,&lt;aiir&gt;
        ///D,&lt;chor&gt;,&lt;dar&gt;,&lt;oly&gt;
        ///E,&lt;dar&gt;,&lt;qo&gt;,&lt;ain&gt;
        ///F,&lt;shal&gt;,&lt;osh&gt;,&lt;do&gt;
        ///G,&lt;shar&gt;,&lt;orch&gt;,&lt;eeam&gt;
        ///H,&lt;shy&gt;,&lt;qoch&gt;,&lt;eeoy&gt;
        ///I,&lt;otedy&gt;,&lt;ych&gt;,&lt;o&gt;
        ///L,&lt;saiin&gt;,&lt;ykch&gt;,&lt;edair&gt;
        ///M,&lt;sain&gt;,&lt;aiiin&gt;,&lt;eedar&gt;
        ///N,&lt;dy&gt;,&lt;oly&gt;,&lt;eod&gt;
        ///O,&lt;y&gt;,&lt;ody&gt;,&lt;edam&gt;
        ///P,&lt;sheody&gt;,&lt;ofch&gt;,&lt;e&gt;
        ///Q,&lt;shody&gt;,&lt;es&gt;,&lt;ols&gt;
        ///R,&lt;sheol&gt;,&lt;ysh&gt;,&lt;eeor&gt;
        ///S,&lt;shol&gt;,&lt;chcth&gt;,&lt;eed&gt;
        ///T,&lt;sheey&gt;,&lt;ar&gt;,&lt;ees&gt;
        ///U,&lt;sheedy&gt;,&lt;op&gt;,&lt;eal&gt;
        ///V,&lt;shor&gt;,&lt;dyk&gt;,&lt;sd&gt;
        ///X,&lt;shaiin&gt;,&lt;qolsh&gt;,&lt;ch&gt;
        ///Y,&lt;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranslationTable_Beta3 {
            get {
                return ResourceManager.GetString("TranslationTable_Beta3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter,Unigram,Prefix,Suffix
        ///A,&lt;chol&gt;,&lt;chckh&gt;,&lt;dal&gt;
        ///B,&lt;qotchdy&gt;,&lt;psh&gt;,&lt;eeed&gt;
        ///C,&lt;sar&gt;,&lt;qofch&gt;,&lt;ail&gt;
        ///D,&lt;chckhey&gt;,&lt;qol&gt;,&lt;eeeody&gt;
        ///E,&lt;chckhy&gt;,&lt;dsh&gt;,&lt;ear&gt;
        ///F,&lt;qotchey&gt;,&lt;qotsh&gt;,&lt;eel&gt;
        ///G,&lt;qotchy&gt;,&lt;sy&gt;,&lt;ok&gt;
        ///H,&lt;qotchedy&gt;,&lt;ory&gt;,&lt;eedam&gt;
        ///I,&lt;raiin&gt;,&lt;sal&gt;,&lt;od&gt;
        ///L,&lt;qotal&gt;,&lt;qokch&gt;,&lt;daly&gt;
        ///M,&lt;qotar&gt;,&lt;q&gt;,&lt;dor&gt;
        ///N,&lt;dair&gt;,&lt;aiir&gt;,&lt;eees&gt;
        ///O,&lt;air&gt;,&lt;solk&gt;,&lt;dair&gt;
        ///P,&lt;qoty&gt;,&lt;qor&gt;,&lt;eoly&gt;
        ///Q,&lt;qotol&gt;,&lt;air&gt;,&lt;ealy&gt;
        ///R,&lt;qoteedy&gt;,&lt;qop&gt;,&lt;dam&gt;
        ///S,&lt;qoteey&gt;,&lt;ytch&gt;,&lt;an&gt;
        ///T,&lt;qotaiin&gt;,&lt;rch&gt;,&lt;ary&gt;
        ///U,&lt;qotain&gt;,&lt;ckh&gt;,&lt;ee&gt;
        ///V,&lt;qotey&gt;,&lt;da&gt;,&lt;aiis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranslationTable_Gamma1 {
            get {
                return ResourceManager.GetString("TranslationTable_Gamma1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter,Unigram,Prefix,Suffix
        ///A,&lt;cheol&gt;,&lt;al&gt;,&lt;aly&gt;
        ///B,&lt;olkchdy&gt;,&lt;ary&gt;,&lt;eom&gt;
        ///C,&lt;lchey&gt;,&lt;olt&gt;,&lt;esy&gt;
        ///D,&lt;olkedy&gt;,&lt;sair&gt;,&lt;a&gt;
        ///E,&lt;lchedy&gt;,&lt;lsh&gt;,&lt;dar&gt;
        ///F,&lt;olkchey&gt;,&lt;dair&gt;,&lt;sairy&gt;
        ///G,&lt;olkchy&gt;,&lt;dyt&gt;,&lt;iir&gt;
        ///H,&lt;olkchedy&gt;,&lt;qocth&gt;,&lt;eer&gt;
        ///I,&lt;qotedy&gt;,&lt;olsh&gt;,&lt;m&gt;
        ///L,&lt;olkal&gt;,&lt;ockh&gt;,&lt;eesy&gt;
        ///M,&lt;olkar&gt;,&lt;d&gt;,&lt;eeal&gt;
        ///N,&lt;dam&gt;,&lt;os&gt;,&lt;eain&gt;
        ///O,&lt;am&gt;,&lt;oksh&gt;,&lt;aim&gt;
        ///P,&lt;olky&gt;,&lt;chcph&gt;,&lt;ais&gt;
        ///Q,&lt;olkol&gt;,&lt;oiiin&gt;,&lt;oiiin&gt;
        ///R,&lt;olkeedy&gt;,&lt;otch&gt;,&lt;eear&gt;
        ///S,&lt;olkeey&gt;,&lt;ksh&gt;,&lt;os&gt;
        ///T,&lt;olkaiin&gt;,&lt;sor&gt;,&lt;om&gt;
        ///U,&lt;olkain&gt;,&lt;fch&gt;,&lt;eedain&gt;
        ///V,&lt;olkey&gt;,&lt;soiin&gt;,&lt;ee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranslationTable_Gamma2 {
            get {
                return ResourceManager.GetString("TranslationTable_Gamma2", resourceCulture);
            }
        }
    }
}
