//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d9.gnc.core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d9.gnc.core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter,Unigram,Prefix,Suffix
        ///A,ol,sh,aiin
        ///B,qokchdy,dol,l
        ///C,chey,lch,eeey
        ///D,cheey,o,eeody
        ///E,chedy,ch,edy
        ///F,qokchey,shckh,eam
        ///G,qokchy,cph,g
        ///H,qokchedy,qotch,eedal
        ///I,shedy,k,dy
        ///L,qokal,cth,es
        ///M,qokar,l,ody
        ///N,daiin,opch,al
        ///O,aiin,r,or
        ///P,qoky,dch,edar
        ///Q,qokol,dl,iin
        ///R,qokeedy,t,eedy
        ///S,qokeey,lk,ar
        ///T,qokaiin,qok,y
        ///U,qokain,ot,eey
        ///V,qokey,qockh,edor
        ///X,qokor,lpch,edo
        ///Y,qokdy,ry,oin
        ///Z,qokeeedy,ols,eeaiin
        ///.
        /// </summary>
        internal static string TranslationTable_Alpha {
            get {
                return ResourceManager.GetString("TranslationTable_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter,Unigram,Prefix,Suffix
        ///A,or,yt,eol
        ///B,okchdy,qolch,ory
        ///C,okedy,tsh,r
        ///D,cheedy,dal,eeos
        ///E,ar,ok,ey
        ///F,okchey,rsh,iiin
        ///G,okchy,solch,eols
        ///H,okchedy,oiin,er
        ///I,qokedy,yk,eody
        ///L,okal,ypch,eedaiin
        ///M,okar,s,edain
        ///N,dal,kch,d
        ///O,al,lkch,eos
        ///P,oky,qoksh,as
        ///Q,okol,of,als
        ///R,okeedy,tch,daiin
        ///S,okeey,or,eeo
        ///T,okaiin,pch,am
        ///U,okain,olk,eo
        ///V,okey,daly,sy
        ///X,okor,f,eeeos
        ///Y,okdy,sok,eory
        ///Z,okeeedy,lfch,eds
        ///.
        /// </summary>
        internal static string TranslationTable_Beta1 {
            get {
                return ResourceManager.GetString("TranslationTable_Beta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter,Unigram,Prefix,Suffix
        ///A,qol,olch,air
        ///B,otchdy,dor,oy
        ///C,lkaiin,y,aiiin
        ///D,lkain,otsh,dol
        ///E,dar,ol,ol
        ///F,otchey,ly,daiiin
        ///G,otchy,ssh,saiin
        ///H,otchedy,aly,eaiin
        ///I,shey,qot,eor
        ///L,otal,sch,edol
        ///M,otar,shcth,dain
        ///N,dain,okch,oiin
        ///O,ain,lt,eeedy
        ///P,oty,qolk,eeod
        ///Q,otol,dary,edaiiin
        ///R,oteedy,qopch,s
        ///S,oteey,sol,edal
        ///T,otaiin,od,edaiin
        ///U,otain,p,eeol
        ///V,otey,sar,sdy
        ///X,otor,do,ery
        ///Y,otdy,olpch,osy
        ///Z,oteeedy,om,eda
        ///.
        /// </summary>
        internal static string TranslationTable_Beta2 {
            get {
                return ResourceManager.GetString("TranslationTable_Beta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter,Unigram,Prefix,Suffix
        ///A,chdy,ls,ed
        ///B,sheckhy,octh,eoy
        ///C,shckhy,och,aiir
        ///D,chor,dar,oly
        ///E,dar,qo,ain
        ///F,shal,osh,do
        ///G,shar,orch,eeam
        ///H,shy,qoch,eeoy
        ///I,otedy,ych,o
        ///L,saiin,ykch,edair
        ///M,sain,aiiin,eedar
        ///N,dy,oly,eod
        ///O,y,ody,edam
        ///P,sheody,ofch,e
        ///Q,shody,es,ols
        ///R,sheol,ysh,eeor
        ///S,shol,chcth,eed
        ///T,sheey,ar,ees
        ///U,sheedy,op,eal
        ///V,shor,dyk,sd
        ///X,shaiin,qolsh,ch
        ///Y,shain,opsh,yl
        ///Z,sheeey,daiir,ady
        ///.
        /// </summary>
        internal static string TranslationTable_Beta3 {
            get {
                return ResourceManager.GetString("TranslationTable_Beta3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter,Unigram,Prefix,Suffix
        ///A,chol,chckh,dal
        ///B,qotchdy,psh,eeed
        ///C,sar,qofch,ail
        ///D,chckhey,qol,eeeody
        ///E,chckhy,dsh,ear
        ///F,qotchey,qotsh,eel
        ///G,qotchy,sy,ok
        ///H,qotchedy,ory,eedam
        ///I,raiin,sal,od
        ///L,qotal,qokch,daly
        ///M,qotar,q,dor
        ///N,dair,aiir,eees
        ///O,air,solk,dair
        ///P,qoty,qor,eoly
        ///Q,qotol,air,ealy
        ///R,qoteedy,qop,dam
        ///S,qoteey,ytch,an
        ///T,qotaiin,rch,ary
        ///U,qotain,ckh,ee
        ///V,qotey,da,aiis
        ///X,qotor,dk,dl
        ///Y,qotdy,sk,ry
        ///Z,qoteeedy,so,in
        ///.
        /// </summary>
        internal static string TranslationTable_Gamma1 {
            get {
                return ResourceManager.GetString("TranslationTable_Gamma1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter,Unigram,Prefix,Suffix
        ///A,cheol,al,aly
        ///B,olkchdy,ary,eom
        ///C,lchey,olt,esy
        ///D,olkedy,sair,a
        ///E,lchedy,lsh,dar
        ///F,olkchey,dair,sairy
        ///G,olkchy,dyt,iir
        ///H,olkchedy,qocth,eer
        ///I,qotedy,olsh,m
        ///L,olkal,ockh,eesy
        ///M,olkar,d,eeal
        ///N,dam,os,eain
        ///O,am,oksh,aim
        ///P,olky,chcph,ais
        ///Q,olkol,oiiin,oiiin
        ///R,olkeedy,otch,eear
        ///S,olkeey,ksh,os
        ///T,olkaiin,sor,om
        ///U,olkain,fch,eedain
        ///V,olkey,soiin,eeeo
        ///X,olkor,x,eedo
        ///Y,olkdy,ail,yr
        ///Z,olkeeedy,chcfh,alsy
        ///.
        /// </summary>
        internal static string TranslationTable_Gamma2 {
            get {
                return ResourceManager.GetString("TranslationTable_Gamma2", resourceCulture);
            }
        }
    }
}
